### ISSUE TITLE
Multilingual descriptions/titles in Páhkat not fetched/used

### ISSUE THREAD

**Issue by snomos** [borealium/borealium.org#14]
See https://borealium.org/nb/language/se/. Cf [this commit](https://github.com/divvun/pahkat.uit.no-index/commit/fe17b6ec920be58e11a824d30d31e0032694b4de).

Expected: title and description in bokmål.

**Comment by snomos** [comment]
Hm, this might actually be a caching/rebuild issue in Páhkat. WDYT @bbqsrc ?

**Comment by bbqsrc** [comment]
Unless a package was published with the strings in `nb`, it won’t show up. If you’ve done that then it’s a bug

**Comment by snomos** [comment]
There’s a new bug in the CI scripts that stops all builds. We’ll see when that bug is fixed whether that was it, or there’s a bug in the Borealium code.

**Comment by snomos** [comment]
This is not an issue. It worked as it should as soon as the Páhkat index was updated.
