### ISSUE TITLE
Link in flt file not rendered as link

### ISSUE THREAD

**Issue by snomos** [borealium/borealium.org#15]
See https://github.com/borealium/borealium.org/commit/ba0e153d7221f34ebfe5a4b5b6eaf11f0feb3688 which contains a link in Markdown format.

The resulting page https://borealium.org/en/privacy/ renders the link text literally, not as a real link.

**Comment by bbqsrc** [comment]
Same as https://github.com/borealium/borealium.org/commit/2f33bee6a3ab62da8b054d2f2e12ebdb92c138c3
