### ISSUE TITLE
Paragraph breaks in flt file not respected

### ISSUE THREAD

**Issue by snomos** [borealium/borealium.org#16]
https://github.com/borealium/borealium.org/commit/1082d0b4a742a3cd3c10f0f36e2bb4a14a71bb8d adds a blank line, with the intention of rendering the following text as a new paragraph. But in https://borealium.org/en/privacy/ it is still one paragraph, not two.

**Comment by snomos** [comment]
This works as expected in `src/index.en.flt` (e.g. for the key `more-info-spellers`), rendered a.o. on the page https://borealium.org/en/resource/speller-sme/.

The same structure does NOT work for `src/privacy/index.en.flt` for whatever reason.

**Comment by bbqsrc** [comment]
```
          {moreInfo != null && (
            <div
              className="section"
              dangerouslySetInnerHTML={{ __html: marked.parse(dedent(moreInfo)) }}
            />
          )}```

It wasn't generalised for other use cases apparently.

**Comment by bbqsrc** [comment]
When you want to explicitly parse the input as Markdown, use the `tmd` function now. https://github.com/borealium/borealium.org/commit/2f33bee6a3ab62da8b054d2f2e12ebdb92c138c3
