### ISSUE TITLE
Redirecting not working

### ISSUE THREAD

**Issue by snomos** [borealium/borealium.org#17]
To repeat:

1. Using a smartphone, open an app with a built-in web view, like Zulip
1. Click on a link to open the web view, and navigate to the GitHub repository for Borealium
1. Click on the link to the Borealium.org website

Result: web page does not contain the body text, instead a text saying _Redirecting…_ appears:

![image](https://github.com/borealium/borealium.org/assets/1255285/996f46a0-4b02-491d-a34f-ee4c1c8fbbf3)

**Comment by bbqsrc** [comment]
In any case, if it can't work it out it'll now fall back to English at least.
