### ISSUE TITLE
South Sámi is not available in the language menu

### ISSUE THREAD

**Issue by albbas** [borealium/borealium.org#21]
sma is defined in data/languages.ts, but is not available in the language menu.

**Comment by snomos** [comment]
This is due to this line: 

https://github.com/borealium/borealium.org/blob/d5e1c2dcf92917fe722222adc7bccb2b8f304585/data/languages.ts#L172

The idea is that languages that have not been properly localised yet should not be listed in the menu. I will make SMA available again.

**Comment by snomos** [comment]
It still does not show up in the language menu after I enabled it. I assume it is because [exactly 0% is translated](https://divvun-pontoon-vm.norwayeast.cloudapp.azure.com/sma/borealium/).
