### ISSUE TITLE
Rekkefølge på ressurssider

### ISSUE THREAD

**Issue by albbas** [borealium/borealium.org#23]
Kanskje en god idé å ha denne rekkefølgen:
- tastatur
- stavekontroll
- online stavekontroll
- ordbøker
- resten

Nåværende rekkefølge varierer fra språk til språk

**Comment by snomos** [comment]
Rekkjefylgje kor hen? Kan du leggja ved skjermbilete eller ein referanse?

**Comment by albbas** [comment]
I ressursoversiktene for språk, f.eks https://borealium.org/nb/language/se/

**Comment by snomos** [comment]
@bbqsrc what governs the order of resource listings?

**Comment by snomos** [comment]
Answer from @bbqsrc offline:

> Probably just the order they’re found

or:

> I think it might be category ordered
> Then id
> It’ll be something simple like this

Feel free to sort the items programmatically as you see fit @albbas

**Comment by snomos** [comment]
Eg trur at det vil fungera enno betre om vi legg inn kategoriane som mellomoverskrifter, slik at strukturen på sida blir noko i stil med:

# Ressursar for X

## Tastatur 

- tastatur 1
- tastatur 2

## Stavekontrollar

- stavekontroll 1
- stavekontroll 2

... osb

**Comment by snomos** [comment]
Dette er no gjort, men bør endrast slik at kategorinamna ser ut som dei gjer andre stader, i stil med:

![image](https://github.com/user-attachments/assets/205b1862-6bdc-4171-9496-4a6102b2ddce)

Då skulle strukturskissa over sjå ut som noko i stil med:

![image](https://github.com/user-attachments/assets/3bbe2e27-c075-4394-9654-f7206da7db24)

- tastatur 1
- tastatur 2

![image](https://github.com/user-attachments/assets/2fc214d9-f6c4-4013-a3a6-97beffcfb3b4)

- stavekontroll 1
- stavekontroll 2

... osb
