### ISSUE TITLE
About us page sme

### ISSUE THREAD

**Issue by werewug** [borealium/borealium.org#25]
Broken code? 
https://borealium.org/se/about/

**Comment by snomos** [comment]
This seems to be a bug in the underlying machinery, caused by non-ASCII characters in the yaml header. At least that is the only difference I can see compared to all the other about docs. Enclsing the string in quotes did not help. @bbqsrc now it is your turn.

**Comment by bbqsrc** [comment]
It was a missing dash at the beginning of the file. You had entirely invalid YAML, lol.
