### ISSUE TITLE
Language selection menu popover does not work in Safari

### ISSUE THREAD

**Issue by snomos** [borealium/borealium.org#33]
Language selection menu should have localised language name as popover/help text. The data is there, and it will help reduce confusion for users.

**Comment by albbas** [comment]
When the langage selection menu is open, and I hover above language names for a few seconds, a popover appears with the localised name. Is that what you mean, or is it the language menu button (when the language menu is closed) that should have a popover?

**Comment by snomos** [comment]
> When the langage selection menu is open, and I hover above language names for a few seconds, a popover appears with the localised name. Is that what you mean

Yes.

And it turns out that this is browser specific. It works in:

- Chrome
- Firefox

It does NOT work in Safari.

All of this on the Mac.

**Comment by albbas** [comment]
This is the site on my Mac, using Safari. Seems to work.

https://github.com/user-attachments/assets/3c7fce5e-a41b-49a0-8db9-323ffb8ba8d6

**Comment by snomos** [comment]
Then it has to be something on my machine. Very confusing 😄 

In any case, this is a non-bug, so I will close it.
