### ISSUE TITLE
Why is only macOS keyboard listed?

### ISSUE THREAD

**Issue by snomos** [borealium/borealium.org#4]
![image](https://github.com/borealium/borealium.org/assets/1255285/5a15f1d0-eae3-4851-a38b-65f9aab3c5cb)

**Comment by snomos** [comment]
Could it be because they have different version numbers?

I notice that spellers list all platforms, but in that case they all have the same version number.

**Comment by bbqsrc** [comment]
It is because they have different version numbers, yes. This is a kinda hard problem to solve because of how Pahkat's metadata is structured. Solvable, just annoying number of loops.

**Comment by bbqsrc** [comment]
Fixed.
