### ISSUE TITLE
Focus on search, but no unfocus when dismissed

### ISSUE THREAD

**Issue by snomos** [borealium/borealium.org#6]
On a phone, when tapping the search field, the view zooms in on the field. This is good and as it should be. But when the search is done or dismissed, the view doesn't zoom out again, instead being left in the zoomed state. Cf the video below.

https://github.com/borealium/borealium.org/assets/1255285/9ad57ae2-ef5e-4a24-a7fc-3f9bd91dd5ef

**Comment by bbqsrc** [comment]
That's not a 'feature' of the website, that's just iOS being iOS.

**Comment by bbqsrc** [comment]
Fixed with 16px font size
